---
title: "cleaning and manipulating data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
library(readr)
```

* Data Sources

+ read in the data
```{r}
catch_original<-read_csv("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1")
```


* Clean and Reshape data

+ remove unnecessary columns
```{r}
catch_data <- catch_original %>% 
  select(Region, Year, Chinook, Sockeye, Coho, Pink, Chum)

head(catch_data)
```
```{r}
catch_data <- catch_original %>% 
  select(-All, -notesRegCode)

head(catch_data)
```
```{r}
glimpse(catch_data)
```

+ check column typing

```{r}
catch_clean <- catch_data %>% 
  mutate(Chinook = as.numeric(Chinook))
```
```{r}
i <- which(is.na(catch_clean$Chinook))
```

```{r}
catch_data[i,]
```

```{r}
catch_clean <- catch_data %>% 
  mutate(Chinook = if_else(Chinook == "I", 1, as.numeric(Chinook)))
```

```{r}
catch_clean[i,]
```

+ reshape data
```{r}
catch_long <- catch_clean %>% 
  pivot_longer(cols = -c(Region, Year), names_to = "species", values_to = "catch")

head(catch_long)
```

```{r}
catch_wide <- catch_long %>% 
  pivot_wider(names_from = species, values_from = catch)

head(catch_wide)
```

```{r}
catch_long <- catch_long %>% 
  rename(catch_thousands = catch)

head(catch_long)
```

```{r}
mean_region <- catch_long %>% 
  group_by(Region) %>%
  summarise(catch_mean = mean(catch))

head(mean_region)
```

```{r}
n_region <- catch_long %>% 
  group_by(Region) %>%
  summarize(n = n())

head(n_region)
```

```{r}
sd_region <- catch_long %>% 
  group_by(Region) %>%
  summarise(catch_sd = sd(catch))

head(sd_region)
```

```{r}
mean_region_by_species <- catch_long %>% 
  group_by(Region, species) %>% 
  summarise(catch_mean = mean(catch))
            
head(mean_region_by_species)
```
```{r}
SSE_catch <- catch_long %>% 
  filter(Region == "SSE")

head(SSE_catch)
```
```{r}
mean_region <- catch_long %>% 
  group_by(Region) %>%
  summarise(catch_mean = mean(catch)) %>% 
  arrange(catch_mean)

head(mean_region)
```

* Join to Regions dataset

```{r}
region_defs <- read_csv("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.303.1") %>% 
    select(code, mgmtArea)

head(region_defs)
```

```{r}
catch_joined <- left_join(catch_long, region_defs, by = c("Region" = "code"))

head(catch_joined)
```

```{r}
sites_df <- data.frame(site = c("HAW-101",
                                "HAW-103",
                                "OAH-320",
                                "OAH-219",
                                "MAI-039"))

sites_df %>% 
  separate(site, c("island", "site_number"), "-")
```

```{r}
dates_df <- data.frame(year = c("1930",
                                "1930",
                                "1930"),
                       month = c("12",
                                "12",
                                "12"),
                       day = c("14",
                               "15",
                               "16"))

dates_df %>% 
  unite(date, year, month, day, sep = "-")
```

